name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Setup Stack
      uses: mstksg/setup-stack@v1
    - name: Install dependencies
      run: |
        stack setup --stack-yaml=stack.yaml
    - name: Build
      run: |
        stack build
    - name: Run tests
      run: |
        stack test
